#!/bin/bash
# Push the bulky halves of the v2.2 release from balfrin straight to the EWC object store.
#
# Runs ON balfrin, which has direct internet to the ECMWF endpoint (verified: HTTP 200) and the
# `ewc` aws profile already in ~/.aws (mode 600, put there by the operator). Nothing bulky therefore
# has to transit a workstation: only the HTML (~250 MB) does, because the web VM's ssh key lives
# there and not here.
#
# What goes where, and why:
#   data/      -> the bucket. ~235 000 per-day payloads, ~80 GB. The web VM has 28 GB free on /, so
#                 this could never live beside the HTML; station.html bakes the bucket base into
#                 window.__payloadBase so the panel fetches them from here.
#   ombsens/   -> the bucket. Regenerated by the add-ons job from the v2.2 caches, so these REPLACE
#                 the v2.0-era images of the same name; without this the new pages would show old
#                 OmB and sensitivity plots under v2.2 numbers.
#   diag/      -> NOT touched. The per-night PNGs are what the interactive panel replaces, and the
#                 classification images under the same prefix are method-independent (the build
#                 lists them from the bucket via _bucket_keys). Deleting them is a separate,
#                 deliberate step -- see doc/reports/13_*.
#
# No --delete anywhere: this release only adds keys. A stale object costs storage; a wrongly
# deleted one costs a re-run.
set -u

SITE="${1:-/scratch/mch/mhrvo/dash_payloads}"
BUCKET="${ALC_S3_BUCKET:-eprofile-alc-dashboard}"
ENDPOINT="${ALC_S3_ENDPOINT:-https://object-store.os-api.cci2.ecmwf.int}"
PROFILE="${ALC_AWS_PROFILE:-ewc}"
export PATH="$PATH:/store_new/mch/msclim/share/software/bin"

# 235 000 small objects: the default 10 concurrent requests would make this take all night.
export AWS_MAX_ATTEMPTS=10
aws configure set default.s3.max_concurrent_requests 64 --profile "$PROFILE" 2>/dev/null || true
aws configure set default.s3.max_queue_size 20000 --profile "$PROFILE" 2>/dev/null || true

if [ ! -d "$SITE/data" ]; then
  echo "REFUSING: $SITE/data does not exist -- build the site first" >&2
  exit 1
fi

echo "site:     $SITE"
echo "bucket:   s3://$BUCKET  ($ENDPOINT)"
echo -n "payloads: "; find "$SITE/data" -name '*.json' | wc -l
echo -n "size:     "; du -sh "$SITE/data" | cut -f1

rc=0
for leg in data ombsens; do
  [ -d "$SITE/$leg" ] || { echo "-- $leg: absent, skipped"; continue; }
  echo "=== syncing $leg ..."
  t0=$SECONDS
  aws --profile "$PROFILE" --endpoint-url "$ENDPOINT" \
      s3 sync "$SITE/$leg" "s3://$BUCKET/$leg" --only-show-errors --size-only
  r=$?
  echo "-- $leg rc=$r in $(( (SECONDS - t0) / 60 )) min"
  [ $r -ne 0 ] && rc=$r
done

echo "=== verification"
for leg in data ombsens; do
  [ -d "$SITE/$leg" ] || continue
  loc=$(find "$SITE/$leg" -type f | wc -l)
  rem=$(aws --profile "$PROFILE" --endpoint-url "$ENDPOINT" \
        s3 ls "s3://$BUCKET/$leg/" --recursive --summarize 2>/dev/null \
        | awk '/Total Objects:/{print $3}')
  echo "  $leg: local $loc  remote $rem"
done
echo "ALC_V22_S3_DONE rc=$rc"
exit $rc
