"""
run_l1_validation.py — multi-instrument inter-comparison from L1 + the CSCS calibration.

For each benchmark site we read the native **L1** range-corrected signal `rcs_0` over **2025-2026**,
turn it into attenuated backscatter by APPLYING the CSCS calibration

    beta_att [Mm^-1 sr^-1] = rcs_0 / C_L * 1e6

where `C_L` is the CSCS Kalman lidar constant straight from the calout `<key>_kalman.csv` (Rayleigh or
cloud, both stored as C_L). Then the operational water-vapour (910 nm) + wavelength corrections,
cloud/fog screening, hourly + common-altitude gridding, and bias/RMSE/relative-bias/r vs the site
reference channel (CHM15k Rayleigh), exactly as the L2 inter-comparison — but NO L2 product and NO raw
vendor files are used. This is a direct end-to-end test of the calibration applied to the raw signal.

Usage:  python -m validation.paper.run_l1_validation [site ...]   (default: all STATIONS)
"""
from __future__ import annotations
import sys
from datetime import datetime
from pathlib import Path

import numpy as np

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

from validation.paper import intercompare as IC
from validation.paper import figures as FIG
from validation.paper.calib_benchmark import BENCHMARK, key_of
from validation.paper.run_paper_validation import STATIONS, SITE_NAME, OUT

REPO = Path(__file__).resolve().parents[2]
START, END = "20250101", "20260623"     # L1 validation period (2025-2026)


def _d(s):
    return datetime.strptime(s, "%Y%m%d").strftime("%Y-%m-%d")


def run_station_l1(name):
    st = BENCHMARK[name]; sc = STATIONS[name]
    chans = []
    for c in st["channels"]:
        d = dict(wmo=c["wmo"], ident=c["ident"], calib=c["calib"], label=c["label"],
                 itype=c["itype"], key=key_of(c))
        if sc["molaer"] and c["label"] == sc["molaer"]:
            d["wavelengthModel"] = "molaer"
        chans.append(d)
    cfg = dict(wmo=sc["wmo"], start=START, end=END, referenceChannel=sc["ref"], channels=chans,
               lambda_target=sc["target"], alpha=1.0, zMin=500, zMax=3000, dataLevel="L1")
    return IC.process(cfg), cfg


def main():
    sites = [a for a in sys.argv[1:] if a in STATIONS] or list(STATIONS)
    rows = []
    for name in sites:
        print(f"== {name} [L1 2025-2026] ==", flush=True)
        R, cfg = run_station_l1(name)
        if R is None:
            print("   no data"); continue
        for k, ch in enumerate(R["channels"]):
            s = R["stats"][k]
            cl = (1e6 / ch["med_corr"]) if ch["med_corr"] else float("nan")  # med_corr = median(1e6/C_L)
            rows.append(dict(station=name, label=ch["label"], calib=ch["calib"],
                             ref=(k == cfg["referenceChannel"]), relbias=s["relbias_pct"],
                             r=s["r"], n=s["n"], cl=cl))
            print("   %-22s relbias=%+7.1f%%  r=%.3f  N=%7d  C_L~%.3g"
                  % (ch["label"], s["relbias_pct"], s["r"], s["n"], cl), flush=True)
        title = "%s (%s) — L1 2025-2026 + CSCS calibration (beta = rcs_0 / C_L)" % (
            SITE_NAME.get(name, name) or name, STATIONS[name]["wmo"])
        FIG.fig_multi_alc(R, cfg, OUT / f"fig_l1_{name}.png", title)
        print(f"   -> fig_l1_{name}.png", flush=True)
    write_report(rows, sites)
    print("L1_VALIDATION_DONE", flush=True)


def write_report(rows, sites):
    L = ["# L1 attenuated-backscatter validation — CSCS calibration applied to the raw signal\n",
         "*Generated by `validation/paper/run_l1_validation.py`. For every channel the **native L1** "
         "range-corrected signal `rcs_0` (2025-2026, `D:/E-PROFILE_L1_2026`) is converted to attenuated "
         "backscatter by applying the **CSCS calibration** — `beta_att = rcs_0 / C_L * 1e6`, with `C_L` "
         "the Kalman lidar constant from the CSCS calout `<key>_kalman.csv` — then water-vapour (910 nm), "
         "wavelength normalisation, cloud/fog screening, hourly + common-altitude gridding, and statistics "
         "over 500-3000 m AGL vs the site reference (CHM15k Rayleigh). No L2 product and no raw vendor "
         "files are used. CL61 is shown under both its cloud and Rayleigh calibrations.*\n",
         "| site | channel | calib | rel. bias | r | N | median C_L |",
         "|---|---|---|---|---|---|---|"]
    for r in rows:
        tag = " *(ref)*" if r["ref"] else ""
        cl = ("%.3g" % r["cl"]) if np.isfinite(r["cl"]) else "—"
        L.append("| %s | %s%s | %s | %+.1f%% | %.3f | %d | %s |"
                 % (SITE_NAME.get(r["station"], r["station"]) or r["station"], r["label"], tag,
                    r["calib"], r["relbias"], r["r"], r["n"], cl))
    # Publish COMPACT copies of the figures next to the report (doc/reports/figs_l1/) so they render in
    # any markdown viewer -- the full-res PNGs in OUT are large and outside the repo workspace (VS Code's
    # preview blocks those). Relative `figs_l1/...` links then resolve from the report's own folder.
    figdir = REPO / "doc" / "reports" / "figs_l1"; figdir.mkdir(parents=True, exist_ok=True)
    try:
        from PIL import Image
    except Exception:
        Image = None
    L.append("")
    for name in sites:
        if not any(rr["station"] == name for rr in rows):
            continue
        src = OUT / f"fig_l1_{name}.png"
        if src.exists():
            dst = figdir / f"fig_l1_{name}.png"
            try:
                if Image is not None:
                    im = Image.open(src); w, h = im.size
                    if w > 1800:
                        im = im.resize((1800, int(h * 1800 / w)), Image.LANCZOS)
                    im.convert("RGB").save(dst, optimize=True)
                else:
                    import shutil; shutil.copyfile(src, dst)
            except Exception:
                import shutil; shutil.copyfile(src, dst)
        L.append(f"### {SITE_NAME.get(name, name) or name}\n")
        L.append(f"![{name} L1 validation](figs_l1/fig_l1_{name}.png)\n")
    txt = "\n".join(L)
    (OUT / "l1_validation_cscs.md").write_text(txt, encoding="utf-8")
    (REPO / "doc" / "reports" / "l1_validation_cscs.md").write_text(txt, encoding="utf-8")
    print(f"  wrote l1_validation_cscs.md ({len(rows)} channels, {len(sites)} sites)")


if __name__ == "__main__":
    main()
